language: python
python:
  - "3.7"
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libgdal-dev
      - postgresql-9.6-postgis-2.4
      - libsystemd-dev
dist: xenial
sudo: required
env:
  global:
    - export DATABASE_URL="postgis://postgres@localhost/api"
    - export PIP_USE_MIRRORS=true
    - export LOG_DISABLE_JOURNALD=true

cache:
  - pip
  - npm

before_install:
  - pip install -U pipenv

install:
  - npm ci && npm run build
  - pipenv install --dev --deploy

script:
  - black --check .
  - node_modules/.bin/eslint agir
  - python manage.py test -v 2
