language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libgdal-dev
      - postgresql-9.6-postgis-2.3
      - libsystemd-daemon-dev
      - libsystemd-journal-dev
dist: trusty
sudo: required

cache:
  - pip
  - npm

before_install:
  - export DATABASE_URL="postgis://postgres@localhost/api"
  - export PIP_USE_MIRRORS=true
  - export LOG_DISABLE_JOURNALD=true

install:
  - "grep -v systemd requirements.txt | pip install -r /dev/stdin"
  - "npm i"
  - "npm run build"

script: "python manage.py test -v 2"
