language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.4"

before_install:
  - export DATABASE_URL="postgres://postgres@localhost/api"
  - export PIP_USE_MIRRORS=true

install: "pip install -r requirements.txt"

script: "cd src && python manage.py test"
